version: "3.9"

services:
  node:
    image: node:lts-alpine
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      #- /app/node_modules
    working_dir: /app
    command: sh -c "npm rebuild esbuild && npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true